import React, { Component } from "react";
import M from "materialize-css";
import "./U_pickcountry.css";

export class PickCountry extends Component {
  constructor(props) {
    super(props);
    this.countryInput = React.createRef();
  }
  componentDidMount() {
    document.addEventListener("DOMContentLoaded", function() {
      const elems = document.querySelectorAll(".autocomplete");
      M.Autocomplete.init(elems, countries);
    });
    console.log(countries);
  }

  render() {
    return (
      <div class="row">
        <div class="col s12">
          <div class="row">
            <div class="input-field col s12">
              <input
                type="text"
                id="autocomplete-input"
                ref={this.countryInput}
                class="autocomplete"
              />
              <label for="autocomplete-input">Destination Country</label>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default PickCountry;
const countries = {
  data: {
    Afghanistan: null,
    Albania: null,
    Algeria: null,
    Andorra: null,
    Angola: null,
    Anguilla: null,
    "Antigua & Barbuda": null,
    Argentina: null,
    Armenia: null,
    Aruba: null,
    Australia: null,
    Austria: null,
    Azerbaijan: null,
    Bahamas: null,
    Bahrain: null,
    Bangladesh: null,
    Barbados: null,
    Belarus: null,
    Belgium: null,
    Belize: null,
    Benin: null,
    Bermuda: null,
    Bhutan: null,
    Bolivia: null,
    "Bosnia & Herzegovina": null,
    Botswana: null,
    Brazil: null,
    "British Virgin Islands": null,
    Brunei: null,
    Bulgaria: null,
    "Burkina Faso": null,
    Burundi: null,
    Cambodia: null,
    Cameroon: null,
    Canada: null,
    "Cape Verde": null,
    "Cayman Islands": null,
    "Central Arfrican Republic": null,
    Chad: null,
    Chile: null,
    China: null,
    Colombia: null,
    Congo: null,
    "Cook Islands": null,
    "Costa Rica": null,
    "Cote D Ivoire": null,
    Croatia: null,
    Cuba: null,
    Curacao: null,
    Cyprus: null,
    "Czech Republic": null,
    Denmark: null,
    Djibouti: null,
    Dominica: null,
    "Dominican Republic": null,
    Ecuador: null,
    Egypt: null,
    "El Salvador": null,
    "Equatorial Guinea": null,
    Eritrea: null,
    Estonia: null,
    Ethiopia: null,
    "Falkland Islands": null,
    "Faroe Islands": null,
    Fiji: null,
    Finland: null,
    France: null,
    "French Polynesia": null,
    "French West Indies": null,
    Gabon: null,
    Gambia: null,
    Georgia: null,
    Germany: null,
    Ghana: null,
    Gibraltar: null,
    Greece: null,
    Greenland: null,
    Grenada: null,
    Guam: null,
    Guatemala: null,
    Guernsey: null,
    Guinea: null,
    "Guinea Bissau": null,
    Guyana: null,
    Haiti: null,
    Honduras: null,
    "Hong Kong": null,
    Hungary: null,
    Iceland: null,
    India: null,
    Indonesia: null,
    Iran: null,
    Iraq: null,
    Ireland: null,
    "Isle of Man": null,
    Israel: null,
    Italy: null,
    Jamaica: null,
    Japan: null,
    Jersey: null,
    Jordan: null,
    Kazakhstan: null,
    Kenya: null,
    Kiribati: null,
    Kosovo: null,
    Kuwait: null,
    Kyrgyzstan: null,
    Laos: null,
    Latvia: null,
    Lebanon: null,
    Lesotho: null,
    Liberia: null,
    Libya: null,
    Liechtenstein: null,
    Lithuania: null,
    Luxembourg: null,
    Macau: null,
    Macedonia: null,
    Madagascar: null,
    Malawi: null,
    Malaysia: null,
    Maldives: null,
    Mali: null,
    Malta: null,
    "Marshall Islands": null,
    Mauritania: null,
    Mauritius: null,
    Mexico: null,
    Micronesia: null,
    Moldova: null,
    Monaco: null,
    Mongolia: null,
    Montenegro: null,
    Montserrat: null,
    Morocco: null,
    Mozambique: null,
    Myanmar: null,
    Namibia: null,
    Nauro: null,
    Nepal: null,
    Netherlands: null,
    "Netherlands Antilles": null,
    "New Caledonia": null,
    "New Zealand": null,
    Nicaragua: null,
    Niger: null,
    Nigeria: null,
    "North Korea": null,
    Norway: null,
    Oman: null,
    Pakistan: null,
    Palau: null,
    Palestine: null,
    Panama: null,
    "Papua New Guinea": null,
    Paraguay: null,
    Peru: null,
    Philippines: null,
    Poland: null,
    Portugal: null,
    "Puerto Rico": null,
    Qatar: null,
    Reunion: null,
    Romania: null,
    Russia: null,
    Rwanda: null,
    "Saint Pierre & Miquelon": null,
    Samoa: null,
    "San Marino": null,
    "Sao Tome and Principe": null,
    "Saudi Arabia": null,
    Senegal: null,
    Serbia: null,
    Seychelles: null,
    "Sierra Leone": null,
    Singapore: null,
    Slovakia: null,
    Slovenia: null,
    "Solomon Islands": null,
    Somalia: null,
    "South Africa": null,
    "South Korea": null,
    "South Sudan": null,
    Spain: null,
    "Sri Lanka": null,
    "St Kitts & Nevis": null,
    "St Lucia": null,
    "St Vincent": null,
    Sudan: null,
    Suriname: null,
    Swaziland: null,
    Sweden: null,
    Switzerland: null,
    Syria: null,
    Taiwan: null,
    Tajikistan: null,
    Tanzania: null,
    Thailand: null,
    "Timor L'Este": null,
    Togo: null,
    Tonga: null,
    "Trinidad & Tobago": null,
    Tunisia: null,
    Turkey: null,
    Turkmenistan: null,
    "Turks & Caicos": null,
    Tuvalu: null,
    Uganda: null,
    Ukraine: null,
    "United Arab Emirates": null,
    "United Kingdom": null,
    "United States of America": null,
    Uruguay: null,
    Uzbekistan: null,
    Vanuatu: null,
    "Vatican City": null,
    Venezuela: null,
    Vietnam: null,
    "Virgin Islands (US)": null,
    Yemen: null,
    Zambia: null,
    Zimbabwe: null
  }
};
