export const SET_CARDS_VISIBLE = "SET_CARDS_VISIBLE";
export const SET_PLACES_MENU = "SET_PLACES_MENU";
export const SET_CITY = "SET_CITY";
export const SET_COUNTRY = "SET_COUNTRY";
export const SET_IMAGE_URL = "SET_IMAGE_URL";
export const SET_PLACE_SELECTED = "SET_PLACE_SELECTED";
export const GET_COORDINATES = "GET_COORDINATES";
export const GET_PLACE_INFO = "GET_PLACE_INFO";
export const REFRESH_CARDS = "REFRESH_CARDS";
export const REFRESH_DONE = "REFRESH_DONE";
export const DELETE_TRIP = "DELETE_TRIP";
export const DELETE_DONE = "DELETE_DONE";
export const LOAD_DATA_LOCALSTORE = "LOAD_DATA_LOCALSTORE";
export const LOAD_DATA_EXTERNAL = "LOAD_DATA_EXTERNAL";
export const RESET_PLACE_DATA = "RESET_PLACE_DATA";
export const INITIALISE_PLACES = "INITIALISE_PLACES";
export const SAVE_LOCALSTORAGE_DONE = "SAVE_LOCALSTORAGE_DONE";


